### ISSUE TITLE
Some species don't show correctly on the selection menu.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#105]
Patch: 4360
Some species don't show centered (either are too close or too far away) on the selection screen menu. (Puerta, Cerato, Hypo Spino, Hatchling Rex, Sub-Adult Rex, Hatchling Carno, Sub-Adult Carno.)
![20170910181429_1](https://user-images.githubusercontent.com/30121219/30251245-e72c3e1c-9653-11e7-9f4f-5fdd9f75e3f4.jpg)
![20170910181450_1](https://user-images.githubusercontent.com/30121219/30251249-f35f88ba-9653-11e7-9736-04b309acebcb.jpg)
![20170910181512_1](https://user-images.githubusercontent.com/30121219/30251253-ffa10b58-9653-11e7-941f-5dadd2dd617b.jpg)
![20170910181534_1](https://user-images.githubusercontent.com/30121219/30251259-14bd3408-9654-11e7-8452-b0c381f4eca4.jpg)
![20170910181538_1](https://user-images.githubusercontent.com/30121219/30251261-1811209c-9654-11e7-8adb-8a9c5eccaf59.jpg)

**Comment by DirtyBongTokes** [comment]
Need to test on different screen resolutions to see if it could be related
