### ISSUE TITLE
Dryo's leg glitch when it crouches.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#108]
Patch: 4372
Server: NY8
When dryo crouches and moves its right leg flattens.
![20170911143248_2](https://user-images.githubusercontent.com/30121219/30277348-673cd912-96ff-11e7-8bbb-4112591f0c3e.jpg)
![20170911143305_2](https://user-images.githubusercontent.com/30121219/30277368-7cbb91a2-96ff-11e7-922d-df2781eb1418.jpg)
https://youtu.be/3K4Wb69enOc

**Comment by KissenKitten** [comment]
This is not an issue I'm going to be able to fix. This is a retargetted dinosaur and that looks like a bind issue. I can alter the old animation and "hope" that it helps but that's a shot in the dark.
