### ISSUE TITLE
Utah only has a limping animation when fake limping.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#110]
Patch: 4373
Server: Hosted (Testing map)
When utah breaks a leg it doesn't have a limp animation, it only does when it's fake limping.
https://youtu.be/Akem30LM_VQ

**Comment by deathlyrage** [comment]
The Utah also slides while walking and while feign limping. I'm guessing this is related to why its not working.

**Comment by deathlyrage** [comment]
Fixed in 4421
