### ISSUE TITLE
Some species change gender when they grow up.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#111]
Patch: 4376
Server: Any
When players grow to adult, if they're female their gender changes to male.

**Comment by AroraTitania** [comment]
Can confirm that. Happened to my Carno. Selected female, spawned in as male and continued my growthstages as male.

**Comment by 0ida** [comment]
I've not tested it that much that, but what i have seen everytime is when you start as female is happening as described above. But it doesnt get saved into the database and when you relog after your appearance changed, you spawn in correct as female again.

**Comment by deathlyrage** [comment]
Fixed in 4384
