### ISSUE TITLE
(Nesting) Some baby animals get stuck in the nest and camera issues.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#113]
Patch: 4384
Server: NY8 Official
Some baby animals get stuck in the nest when they're born and can't get out of it, making them die of thirst/hunger.
Camera is too zoomed in when in nest and can't be adjusted (it happens in contact with any object(water, food, rocks, trees, nests etc).
[Adding specific species when I'm able to test with all species]
![20170916122421_1](https://user-images.githubusercontent.com/30121219/30512000-db84e914-9adc-11e7-917b-648653ee3e0c.jpg)
![20170916122936_1](https://user-images.githubusercontent.com/30121219/30512001-dded2482-9adc-11e7-80d2-c5f45b66156b.jpg)

**Comment by Paleocolour** [comment]
I have fixed the Maia, but are there any other dinosaurs that get stuck when nesting?

**Comment by MarianaBoni** [comment]
All fine.
