### ISSUE TITLE
Double nesting issue.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#118]
Patch: 4388
Server: NY8 Official
When you place a nest and respawn/progress, that nest doesn't disappear and it's icon will still appear when you respawn (for around 5 seconds) even if you're really far away.
You can access the new nest and invite someone, it says nest destroyed if the first one is still active.
![20170920132815_1](https://user-images.githubusercontent.com/30121219/30644015-deb4cd78-9e08-11e7-9444-3b3350cc7860.jpg)
![20170920114248_1](https://user-images.githubusercontent.com/30121219/30650399-b165fb96-9e1a-11e7-9e63-d505e6ac5553.jpg)

(Images from different species since it was tested with both)

**Comment by deathlyrage** [comment]
Fixed in 4396

**Comment by MarianaBoni** [comment]
Tried this again after the fixed patch, and now it says "not enough eggs" instead of nest destroyed.

**Comment by deathlyrage** [comment]
Fixed in 4415
