### ISSUE TITLE
Older UI still shows when starting game for a split second.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#119]
Patch: 4388
When launching the game, an older UI still shows for around 1 second before the new one appears.
![20170920134051_1](https://user-images.githubusercontent.com/30121219/30644188-825deeaa-9e09-11e7-8529-e0fd6bdc534a.jpg)

**Comment by deathlyrage** [comment]
This is intended as the map is loading in the background.
