### ISSUE TITLE
Calls/roars not playing for other players after attacking (most dinosaurs)

### ISSUE THREAD

**Issue by Souretsu** [deathlyrage/theisle-bugs#12]
With nearly all dinosaurs, if you attack, your calls become bugged.  The next call directly after the attack will play, but every call afterwards will not play for anyone except the player performing them. This problem seems to exclude: Rex, Theri, Trike, Shant, and Galli, all of whom are still able to call afterwards, albeit with an unusual pause (possibly lag).

**Comment by deathlyrage** [comment]
Fixed in 4160
