### ISSUE TITLE
Steam avatar appears white and name tags still show while resting.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#120]
Patch: 4392
When adding someone to group, name tags appear and avatar appears all white.
Name tags and avatars still show while resting.
![20170920152617_1](https://user-images.githubusercontent.com/30121219/30649523-6148a43a-9e18-11e7-9ea0-a9235b5a10ba.jpg)
![20170920152751_1](https://user-images.githubusercontent.com/30121219/30649526-63561c9e-9e18-11e7-9829-c0b4173eece2.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4397
