### ISSUE TITLE
Missing Carno Hatching Skin

### ISSUE THREAD

**Issue by deathlyrage** [deathlyrage/theisle-bugs#123]
Cook: LogInit: Display: LogLinker: Warning: Can't find file '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling'
Cook: LogInit: Display: LogUObjectGlobals: Warning: Failed to load '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling': Can't find file '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling'
Cook: LogInit: Display: LogLinker: Warning: Can't find file for asset '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling' while loading D:/theisle/trunk/Content/Blueprints/Characters/Dinosaurs/Survival/BP_Carnotaurus_Hatchling_S.uasset.
Cook: LogInit: Display: LogUObjectGlobals: Warning: Failed to load 'D:/theisle/trunk/Content/Blueprints/Characters/Dinosaurs/Survival/BP_Carnotaurus_Hatchling_S.uasset': Can't find file for asset '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling' while loading D:/theisle/trunk/Content/Blueprints/Characters/Dinosaurs/Survival/BP_Carnotaurus_Hatchling_S.uasset.
Cook: LogInit: Display: LogLinker: Warning: Can't find file for asset '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling' while loading NULL.
Cook: LogInit: Display: LogUObjectGlobals: Warning: Failed to load '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling': Can't find file for asset '/Game/TheIsle/Characters/Dinosaurs/Carno/Materials/MI_Carno_Hatchling' while loading NULL.

**Comment by Paleocolour** [comment]
Fixed. Awaiting testing.
