### ISSUE TITLE
Server Player list shows 0 ping.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#125]
Patch: 4409
Server: NY1 Official
All players on the player list show 0 ping. 
You can only see your own ping. 
![capture png_2](https://user-images.githubusercontent.com/30121219/30756688-a098930a-9fc3-11e7-9ed4-d1aec7abc85c.PNG)

**Comment by deathlyrage** [comment]
Fixed in 4412
