### ISSUE TITLE
While crouching, players are able to go further into water.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#129]
Patch: 4420
Server: Hosted
While crouching players are able to go deeper into water than they are while walking/trotting/sprinting without starting to swim.
If you uncrouch at a certain place you start swimming.
https://youtu.be/mu5z5FrL_SA

**Comment by Hypno123** [comment]
The player is now forced into swimming regardless of their stance beyond a certain point.
