### ISSUE TITLE
Chatbox enhancement

### ISSUE THREAD

**Issue by DBT666** [deathlyrage/theisle-bugs#133]
Chat-box should close if you don't type anything and hit enter or escape, currently it has a timer if no one is typing and you have to wait for it to close.

E.G.
Hit enter once (open chat box)
Hit enter again with typebox empty (close chat box)

escape should probably have some functionality that doesn't leave chat open and have BP_UMG_EscapeMenu overlapping chatbox

**Comment by deathlyrage** [comment]
Added in 4435
