### ISSUE TITLE
(Nesting) Different species can still see family related icons

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#135]
Patch: 4430
Server: NY8 Official
- When you nest a player, if you respawn/progress to other species, the family icons will still show up.
![20170924112402_1](https://user-images.githubusercontent.com/30121219/30781764-cf7f5a46-a11c-11e7-9409-747c75c01cfc.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4434
