### ISSUE TITLE
Players who progress, are still grouped with the former species.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#136]
Patch: 4430
Server: Any progression server
When you're species x and you're grouped with other species x players, if you progress to species y, you can still see the group tags from players playing species x and talk in group chat.
Example: Velo grouped with other velos, progresses to herra. Herra is still grouped with the velos, seeing their name tags and group chat.

**Comment by deathlyrage** [comment]
Fixed in 4436
