### ISSUE TITLE
Fake Limp animation is sped-up after being used one time.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#138]
Patch: 4444
Server: NY8 Official
After being used one time, every a player fake limps, the going down animation is sped-up. It also seems to happen after certain actions like after trotting. sprinting, getting up from resting, eating, drinking etc.
 (Happens to all species). It doesn't matter how long fake limping is done after those actions, it will still be sped-up.
Example 1 (it being sped up after first fake limp) - https://youtu.be/7lx9emPHajU
Example 2 (it being sped up after actions) - https://youtu.be/mgnxqZgjphM

**Comment by deathlyrage** [comment]
Fixed in 4752
