### ISSUE TITLE
Players disappear when they don't roar on Spectator Mode and Replays.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#141]
Patch: 4452
Server: NY2 Official
On Spectator Mode and Replays, players only show when they roar, disappearing after if you're close.
The time they show also seems inconsistent, sometimes showing one second, other times showing around 4/5 seconds.
https://www.youtube.com/watch?v=zYZYYXqLz_M&feature=youtu.be

**Comment by deathlyrage** [comment]
Fixed in 4490
