### ISSUE TITLE
All nested players appear with the male icon even if they're female

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#144]
Patch: 4456
Server: NY2 Official
All nested players have a male icon even if they selected female on the nesting screen and have female skin.
![20170927182107_1](https://user-images.githubusercontent.com/30121219/30941177-132bcd94-a3dc-11e7-972a-d5e5918765a8.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4462
