### ISSUE TITLE
Species that can jump can do so while resting.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#155]
Patch: 4472
Server: Any
Dryo, Galli, Austro, Herra, Utah and Velo can jump while resting if they press Space Bar followed by H.

https://gyazo.com/1fa6f6d1ad48863625242f1b5d19dc92

**Comment by dinosauriac** [comment]
The movement locks are in the correct spots, they _shouldn't_ be able to initiate a jump until the animation is right near the end.

**Comment by deathlyrage** [comment]
Fixed in 4491
