### ISSUE TITLE
Replay camera stuck inside map and unable to move.

### ISSUE THREAD

**Issue by Reisyns** [deathlyrage/theisle-bugs#159]
**Description:** When you play a Replay, the camera starts you inside a mountain and you are unable to move around.
**Patch:** 0.1.24.4493
**Screenshot:**
![ss 2017-10-08 at 04 13 36](https://user-images.githubusercontent.com/4297087/31315172-aa583b5a-ac45-11e7-8b81-d1d3b25f0d21.png)

**Comment by MarianaBoni** [comment]
Replays are working correctly on hosted servers, only being locked on like the image shows on other servers.
