### ISSUE TITLE
UI is cut on 4:5 screens

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#162]
Patch:4498
Server: 
4:5 screens with 1024x768/1280x1024 resolution have the UI cut off.

![2](https://user-images.githubusercontent.com/30121219/31339452-cfddb67e-acfa-11e7-8435-47b3830708de.jpg)
![1](https://user-images.githubusercontent.com/30121219/31339446-ce11aad0-acfa-11e7-95e2-394e0b208268.jpg)
![0](https://user-images.githubusercontent.com/30121219/31339444-ccec1c26-acfa-11e7-9812-27f0aa231c52.jpg)

**Comment by Paleocolour** [comment]
This is something I always have to get around when I play on my 4:3 monitor. Ideally the new UI will take this into account and scale accordingly. Marking as enhancement.

**Comment by dinosauriac** [comment]
I'm going to call this one fixed. The debug text displayed for coordinates etc. is not really part of the UI and will be replaced by the My Dinosaur screen eventually. Every other instance of HUD / menus now takes non-widescreen monitors into account.
