### ISSUE TITLE
Chat opens behind logout UI.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#165]
Patch:
Server: NY8 Official
When waiting for the logout timer, the chat still opens behind the logout UI.
![20171009152944_1](https://user-images.githubusercontent.com/30121219/31343208-df4c7896-ad06-11e7-9f3a-9e2ba71ee5c5.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4532
