### ISSUE TITLE
Replays showing with 1fps

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#167]
Patch: 4498
Server: NY8 Official
Replays are unwatchable, having only 1 fps.
https://youtu.be/XbIwTFsx0Xc

**Comment by deathlyrage** [comment]
Possible Fix in 4507

**Comment by MarianaBoni** [comment]
Replays now play at 9fps. Character doesn't move, textures don't load and the first roar sound continues forever.
https://youtu.be/X9Xr-mUTrNA
