### ISSUE TITLE
Audio HUD not saving properly

### ISSUE THREAD

**Issue by AroraTitania** [deathlyrage/theisle-bugs#170]
tested on: 
0.1.24.SVN - 2383039 (development)

description:
After changing, applying and closing the volume bars in the Audio section in the options HUD and bringing said HUD back up again, the game doesn't save your changes properly. The sound change is being applied but the HUD shows it wrong. 100% are the last changed vaules you chose.

![20171009173409_1](https://user-images.githubusercontent.com/26965930/31346901-ea8a1e48-ad1a-11e7-998d-b23711bc783e.jpg)

![20171009173348_1](https://user-images.githubusercontent.com/26965930/31346909-f06fe6e4-ad1a-11e7-9717-0dd85e3cb8d0.jpg)

HUD after reopening with changes being made.

**Comment by deathlyrage** [comment]
Fixed in 4531
