### ISSUE TITLE
Players are able to move when Player-list/Settings is open.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#177]
Patch: 4498
Server: NY8 Official
Players are able to move with player-list and settings open, by Opening the player-list/settings, followed by opening the chat, typing/double clicking enter.
https://i.gyazo.com/f4b6c37b0ae5c576ed9a66c47e59a082.gif
https://i.gyazo.com/8da9f3b7640b822c04abe788e5f73def.gif

**Comment by deathlyrage** [comment]
Fixed in 4543
