### ISSUE TITLE
Eating/drinking while alt-turning.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#184]
Patch: 4498
Server: NY8 Official
If you press E while alt-turning, you can eat/drink. (All species)
https://youtu.be/Ge_kPAyhGLg

**Comment by deathlyrage** [comment]
Fixed in 4510

**Comment by MarianaBoni** [comment]
Not fixed on patch 4513:
https://youtu.be/qVVOYE-lnPs

**Comment by deathlyrage** [comment]
Fixed in 4544
