### ISSUE TITLE
Rigid head movements.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#193]
Patch: 4551
Server: NY8 Official
Head movement isn't coordinated to where the camera is pointing.
https://youtu.be/TyXGIVD-Ung

**Comment by MarianaBoni** [comment]
This issue is not present on patch 4564, the head inversion in contact with objects is again.

**Comment by Paleocolour** [comment]
Did this one solve itself @MarianaBoni ? If so, can you close this bug?

**Comment by MarianaBoni** [comment]
Problem appeared when head inversion/bobbing near objects was solved, then with the inversion being back it disappeared.
