### ISSUE TITLE
Oxygen inconsistency

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#197]
Patch: 4564
Server: NY8 Official
Player's head being under water not always triggers the oxygen indicator. Usually actions like drinking/biting will trigger it.
Once it is triggered, even with the player's head above water, it will decrease oxygen, only stopping when your character is 100% outside of the water.
https://youtu.be/1SgzTLcBq68

**Comment by deathlyrage** [comment]
Oxygen system is now disabled, it will be back when this issue is resolved.
