### ISSUE TITLE
Unable to change chat unless you type first.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#201]
Patch: 4578
Server: NY8 Official
To be able to change chats between, local, group and global, the player has to type something first and press enter, so it changes chats and just doesn't write it in chat.
https://youtu.be/rkoyfvSTVQc

**Comment by oOCircleofLifeOo** [comment]
For me it registers the chat change if i press the assigned button even when the chat window isn´t showing. So for example I could log on, press the previous chat button twice and start chatting in global, without having to press enter first. Enter just makes the chat window appear, so you can actually see in wich chat you are in.

**Comment by Hypno123** [comment]
Closing this to open an enhancement that will resolve the issue.
