### ISSUE TITLE
Server List search options not working correctly.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#206]
Patch: 4593
When typing a game mode on the Game Mode field, after refreshing the filter is not applied.
Max results field doesn't return the right number of servers. If a player types 0, no result will be found, but all searches after will have a random number of servers appearing.
https://www.youtube.com/watch?v=3it_ZE81k7o

**Comment by Hypno123** [comment]
Mentioned in #99
