### ISSUE TITLE
(V3) Ambient sound is missing.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#208]
Patch: 4612
Server: NY3 Official
Ambient sound is missing.
https://youtu.be/R3DIA44kXk4

**Comment by dinosauriac** [comment]
So... I'm not going to go adding ambiences until the maps are done, and have yet to properly get stuck into making different setups for different times of day due to other commitments on the project.

**Comment by Paleocolour** [comment]
This has been temporarily 'fixed' as I have added a forest ambience sound cue to the persistent level on V3, but it's definitely not what we want in the final product. I am going to leave this as open for when Richard creates proper ambiences.

**Comment by Hypno123** [comment]
Map no longer in development.
