### ISSUE TITLE
Choosing same starter after extinct screen does not work when relogged

### ISSUE THREAD

**Issue by 0ida** [deathlyrage/theisle-bugs#21]
Server: New Ark 2 [Low-pp/Nest] and several others for testing
Patch: 0.1.15.4101 and previous patch + actual dev branch
Confirmed by: Me, Arora Titania (dev branch)

Issue:

- Choosing the same starter dino after extinct screen does not work when relogging before choosing

Description:
If you die and instantly choose a new Dino after the extinct screen, it works to take the same starter as before. If you logout after the extinct screen and log back in you cant choose the same starter again:
For example: You are a Allo and die. After the extinct screen you click logout. When you login again you are not able to choose Velo. You have to choose Taco/Oro and die again before you can start as Velo. Same problem for Herbs.

Video of the bug: https://youtu.be/lLHQU9oljdA

- Tested on unmodded and modded Servers
- Tested on migrated database and fresh created database
- Tested on newly created servers on different machines
- Tested by Arora Titania on the current dev branch

Update: also tested with Patch 0.1.15.4105

**Comment by deathlyrage** [comment]
Fixed in 4115
