### ISSUE TITLE
(V3) Graphical artifact on landscape.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#213]
Patch: 4612
Server: NY3 Official
Graphical artifact on landscape.
![20171023232452_1](https://user-images.githubusercontent.com/30121219/31916249-a2d43b4e-b849-11e7-9b36-19219804b46f.jpg)
![20171023232345_1](https://user-images.githubusercontent.com/30121219/31916251-a5f07e8c-b849-11e7-968e-ebf986ed55fe.jpg)

**Comment by oOCircleofLifeOo** [comment]
![grafik](https://user-images.githubusercontent.com/28966884/31919953-2e6a4614-b866-11e7-816f-5ef3b95fb498.png)
A video that shows the area where this artifact happens. Seems like the shaders for those areas are way darker/ different.

**Comment by oOCircleofLifeOo** [comment]
https://www.dropbox.com/s/002u56bz7eg4fff/2017-10-24%2002-41-51.mp4?dl=0
A video of the areas where this bug is occuring. Seems like the shaders are diffrent/inverted on those parts but the ground material is the same.

**Comment by YautjaFett** [comment]
A few more spots where this is happening.  This is as of patch 1.28.4635 on NY3.
I have up close screenshots if needed.  
![v3 map texture spots](https://user-images.githubusercontent.com/32628229/32075191-e89d3aa0-ba50-11e7-93e0-ea00cf52f589.jpg)

**Comment by Hypno123** [comment]
Map no longer in development.
