### ISSUE TITLE
(V3) Underwater camera visibility differentiates between drinkable water and salt water.  

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#214]
Patch: 4612
Server: NY3 Official
The visibility of the camera when underwater differentiates between drinkable water (lakes) and salt water (ocean).
Lake example:
![20171024161948_1](https://user-images.githubusercontent.com/30121219/31951952-51828852-b8d7-11e7-9ce2-2eee9774936e.jpg)

Salt water example:
![20171024162000_1](https://user-images.githubusercontent.com/30121219/31951961-556ab4bc-b8d7-11e7-8c35-020d62a7dc57.jpg)

**Comment by Paleocolour** [comment]
It's possible to create a post-processing volume under the ocean plane, but perhaps it's best if this minor thing is taken care of when we do our swimming pass.

**Comment by Hypno123** [comment]
Map no longer in development.
