### ISSUE TITLE
Gallimimus does not do a full attack animation while sprinting.

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#215]
Patch: 4612
Server: NY8 Official
It makes the sound raises it's head and arms, but the legs continue running.
https://youtu.be/l-ldPd8cjvo

**Comment by MarianaBoni** [comment]
The animation does exist it is just sped up, not sure if intended because it is sprinting and a kick while sprinting wouldn't be possible to be as high as per example while walking.

**Comment by YautjaFett** [comment]
Ok, I thought that might be the case.  Should I change the title, delete the post, close it or leave it?
