### ISSUE TITLE
(V3) Gaps in the V3 map 

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#216]
Patch: 4612
Server: NY3 Official
There is a small gap in the map just outside Triplets. 
![20171024022604_1](https://user-images.githubusercontent.com/28966884/31919892-e02b5d1c-b865-11e7-8b9f-fc6a377109d9.jpg)
![v3 map by dondi gap](https://user-images.githubusercontent.com/28966884/31921479-e0f1231c-b86f-11e7-8273-b101210f9956.jpg)

The location is also shown in the Video I attached to Issue #213

**Comment by YautjaFett** [comment]
Patch 4636
Server NY8
Another gap here.
![gap 1 in v3 coords](https://user-images.githubusercontent.com/32628229/32129693-678d450a-bb3f-11e7-8856-ede888cf15a6.png)

**Comment by oOCircleofLifeOo** [comment]
More gaps found. No big deal tho, one is even underwater (Gap 2).
Gap 1: 
![20171028211937_1](https://user-images.githubusercontent.com/28966884/32137875-61137a16-bc28-11e7-99e9-1dee447d8a7a.jpg)
Gap 2: 
![20171028212300_1](https://user-images.githubusercontent.com/28966884/32137876-69a9cc5c-bc28-11e7-8edf-26a1362dd0fd.jpg)

Locations: 
![v3 map gaps](https://user-images.githubusercontent.com/28966884/32137880-785de90e-bc28-11e7-996c-329eceff5480.jpg)
