### ISSUE TITLE
(V3) Mud texture instead of Sand texture on V3

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#217]
Patch: 4612
Server: NY3 Official
There is still some Mud texture left, that should´ve been replaced by sand.
The location is marked on the attached map of V3 and can be seen in the Video.
![v3 map by dondi mud](https://user-images.githubusercontent.com/28966884/31921456-c38de274-b86f-11e7-80f4-24a995b6ec66.jpg)

https://www.dropbox.com/s/3x6df99ovxza3mi/2017-10-24%2003-39-12.mp4?dl=0

Edit: (Patch 4625) The shiny mud texture got changed to the sand texture but it still appears way darker compared to the rest of the sandy areas.
![20171025005646_1](https://user-images.githubusercontent.com/28966884/31972216-d48b3698-b91f-11e7-877c-0b168fbeeb38.jpg)
![20171025005702_1](https://user-images.githubusercontent.com/28966884/31972217-d6a8a802-b91f-11e7-9ca7-cff77e279b37.jpg)

Edit 2: (Patch 4626) It´s shiny and looking like mud texture again. 
![20171025133115_1](https://user-images.githubusercontent.com/28966884/31998686-fa72b360-b990-11e7-875b-1a8676006002.jpg)

**Comment by YautjaFett** [comment]
Patch 4636
Server NY8
Found a lake with mud texture in it.
![ground not blending properly](https://user-images.githubusercontent.com/32628229/32099951-3c01b196-bac7-11e7-9bcb-d09b71a2e928.jpg)

**Comment by MarianaBoni** [comment]
Still present on 4639

**Comment by Hypno123** [comment]
Map no longer in development.
