### ISSUE TITLE
Maia's legs clip into body while walking, trotting and running

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#219]
Patch: 4615
Server: NY8 Official
Legs clip into body with any movement mode and there is a noticeable fold in the thigh with the leg is stretched it's furthest forward during a sprint.
https://youtu.be/7idbESGs_Ow

**Comment by KissenKitten** [comment]
This kind of clipping is relatively expected and doesn't present a stark issue from what I see in the video.
