### ISSUE TITLE
Gallimimus walk-turn bugged.

### ISSUE THREAD

**Issue by Birdskull** [deathlyrage/theisle-bugs#22]
When running or trotting, Gallimimus turns normally. When walking the turning is nearly impossible, resulting in an absurdly large and slow turn. Far too wide and slow to be intended. 

Server: Site B: Restricted
No mods, progression, growth, Battleye enabled. Privately hosted via a server box. 

Patch: 0.1.15.4102
This occurred early today, would have been just after the latest version.

Here's a video- Apologies for the quality. 
https://www.youtube.com/watch?v=yF2TJwT4sVY

-edit- 
The walk turning bug appears to only happen at certain times, because I can turn normally in-game now but another person can't. 
Perhaps this is triggered by some sort of in-game action, and possibly isn't limited to just Gallimimus.

**Comment by Kovacs1** [comment]
Was checked by 2 testers. Could not reproduce.

**Comment by Hypno123** [comment]
Appears to only affect specific servers, namely 'The Association' and 'Site B'.
