### ISSUE TITLE
Galli's legs create a sharp seam and an unnatural dip when resting.

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#220]
Patch: 4615
Server: NY8 Official
Galli's legs fold at the top of the thigh to create a sharp seam and make an unnatural dip low enough that grass clips up and is visible between the legs and body if positioned correctly.
![desktop screenshot 2017 10 23 - 20 34 48 36](https://user-images.githubusercontent.com/32628229/31923861-303753f8-b832-11e7-89a8-ce7e271b61ef.png)

**Comment by YautjaFett** [comment]
Here are some better pictures for clarification.
![galli right leg close up](https://user-images.githubusercontent.com/32628229/31958597-26667852-b8a7-11e7-9b56-5da50cb023df.jpg)
![galli right leg](https://user-images.githubusercontent.com/32628229/31958600-2694897c-b8a7-11e7-919f-95a45c571110.jpg)

**Comment by deathlyrage** [comment]
Won't Fix
