### ISSUE TITLE
(V3) Texture-Issues on V3

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#223]
Patch: .4620
Server: NY3
The middle lake at Triplets has some partial Sand textures on one end.
1
![20171024130251_1](https://user-images.githubusercontent.com/28966884/31940559-e0c7fcea-b8be-11e7-82b1-c73ce5753f96.jpg)

 Edit: There is another area with the same issue. 
2
![20171025033947_1](https://user-images.githubusercontent.com/28966884/31977150-bf443dc2-b93b-11e7-925f-67b0977d79d0.jpg)

Locations: 
![v3 map texture issue](https://user-images.githubusercontent.com/28966884/31977230-156654d8-b93c-11e7-82d9-ba7b930e2d1b.jpg)

**Comment by MarianaBoni** [comment]
First one fixed on 4639
Second one still present:
![20171029104519_1](https://user-images.githubusercontent.com/30121219/32142802-5205e9f0-bc96-11e7-935a-224ad8d62ffd.jpg)

**Comment by Hypno123** [comment]
Map no longer in development.
