### ISSUE TITLE
(V3) Animals not centered on the selection menu.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#228]
Patch: 4621
Server: NY3 Official
Animals on V3's selection screen are not centered/ visible.
Some are way too close to the camera and others too far away.
![20171024154301_1](https://user-images.githubusercontent.com/30121219/31952021-80ef2dca-b8d7-11e7-9d78-8963134540d6.jpg)
![20171024154359_1](https://user-images.githubusercontent.com/30121219/31952038-89c58110-b8d7-11e7-9986-6dacf7717063.jpg)
![20171024154405_1](https://user-images.githubusercontent.com/30121219/31952059-9a6fa284-b8d7-11e7-8c23-d63831acbb88.jpg)
![20171024154403_1](https://user-images.githubusercontent.com/30121219/31952064-9ef93b76-b8d7-11e7-9eea-1f3124769b0c.jpg)
![20171024154310_1](https://user-images.githubusercontent.com/30121219/31952086-ab160b00-b8d7-11e7-808d-3cefc675f6b6.jpg)
![20171024154304_1](https://user-images.githubusercontent.com/30121219/31952090-ae6d60a0-b8d7-11e7-813f-69ee9b7c1d32.jpg)

**Comment by Hypno123** [comment]
Map no longer in development.
