### ISSUE TITLE
(V3) Found an area in V3 where the tree trunks are not submerged.

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#232]
Patch: 4625
Server: NY3
Here are the cords:
![debug location of trees not in ground](https://user-images.githubusercontent.com/32628229/31968266-6fdba6b0-b8c5-11e7-8589-dfa31ebc1c5b.png)

![trees not in the ground](https://user-images.githubusercontent.com/32628229/31968288-880fb622-b8c5-11e7-9d0a-0574b69a50db.png)
![v3 spot where tree trunks are not submerged](https://user-images.githubusercontent.com/32628229/31968324-a98cc16e-b8c5-11e7-8012-ceeb6a68e826.jpg)

**Comment by YautjaFett** [comment]
Another set of trees half out of the ground here:
![tree off ground location](https://user-images.githubusercontent.com/32628229/31974611-73ee9cd2-b8e1-11e7-8630-6529172c241f.png)
![tree off ground](https://user-images.githubusercontent.com/32628229/31974615-7687f9c0-b8e1-11e7-8a3f-5abba55248b6.png)

**Comment by YautjaFett** [comment]
Patch: 4625
Server: NY3
Two more spots:
![trees half out of ground a coords](https://user-images.githubusercontent.com/32628229/31980009-8ffe75f6-b8fe-11e7-9baa-2393e1bd0d24.png)
![trees half out of ground a](https://user-images.githubusercontent.com/32628229/31980010-91dcc2a6-b8fe-11e7-9cc6-1fc2ba30f57c.jpg)
![trees half out of ground b coords](https://user-images.githubusercontent.com/32628229/31980015-94db7d76-b8fe-11e7-918f-b02ca4daff1f.png)
![trees half out of ground b](https://user-images.githubusercontent.com/32628229/31980018-96f1a54a-b8fe-11e7-9fd1-47be31450bc8.png)

**Comment by Hypno123** [comment]
Map no longer in development.
