### ISSUE TITLE
(V3) Flickering Tree line

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#233]
Patch: 4625
Server: NY3
Found a location where the tree line flickers.
https://youtu.be/VNmcKLa4au0
Little circle is where I was, the big circle is where the trees in the video are.
![little circle is my location big circle is the flickering treeline](https://user-images.githubusercontent.com/32628229/31969750-a7d7dd36-b8ca-11e7-9525-d81a05b1f26e.jpg)

**Comment by YautjaFett** [comment]
Patch: 4625
Server: NY3
Another spot here:
https://youtu.be/krx1E2IvSaY
![flickering tree line 2](https://user-images.githubusercontent.com/32628229/31972661-893aece0-b8d6-11e7-9262-1c03f7a5d7ee.jpg)

**Comment by Hypno123** [comment]
Map no longer in development.
