### ISSUE TITLE
(V3) Fog density

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#235]
Patch: 4625
Server: NY3 Official
Fog density issue (footage from the ocean in between triples and marsh, during the transition from night to day).
https://youtu.be/4uW2Baprp60

**Comment by Paleocolour** [comment]
I believe this is an issue with the plane itself somehow, not the fog. It happens any time of day, with any translucent material applied to it, simply look at the plane with different camera angle.

**Comment by Hypno123** [comment]
Map no longer in development.
