### ISSUE TITLE
(V3) Able to get stuck in the same tree

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#236]
Patch: 4625
Server: NY3
Stuck in tree:
https://youtu.be/2vzahZJtxME 
Recreated in the same tree here:
https://youtu.be/7I2xQiAYFss 
Here's the location:
![stuck in tree](https://user-images.githubusercontent.com/32628229/31974064-32adf9f0-b8de-11e7-9310-95a460cee8f9.jpg)

**Comment by oOCircleofLifeOo** [comment]
I had the same thing happen to me as Diablo and Puerta at random locations on the map. I ran into a tree and wasn´t able to move anymore, only able to alt-turn. A relog fixes this bug.

**Comment by Hypno123** [comment]
Map no longer in development.
