### ISSUE TITLE
Experienced an incremental damage increase until death

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#237]
Patch: 4625
Server: NY3
I was nested in by Circle as a Maia and everything was normal as far as I could tell.  I had to leave and logged out so I wouldn't starve.  When I logged back in, I was taking damage as I was growing.  Here is the footage:
https://youtu.be/OgZuT_16cxA

Here are the times and events that I logged:
(These are also in the description of the YouTube video)
Damage Pattern
0.49.39         -14
2.20.35         -15
2.49.73         -16
3.49.41         -17
4.48.96         -19
5.44.03         -20
6.43.81         -21
7.44.40         -22
8.44.00         -23
9.44.91         -24
10.43.57       Death

Growth Pattern
37.47            +8
1.37.73         +8
0.4
2.37.71         +11
3.37.79         +11
4.37.65         +11
5.32.45         +11
6.32.45         +11
7.32.93         +11
8.32.72         +11
9.32.83         +11
10.33.01       +11

1.48.35         ***Jinawee being awesome and using her Isle knowledge to help someone figure something out.***

Here is the location:
![maia was nested here](https://user-images.githubusercontent.com/32628229/31982616-72387584-b90e-11e7-83f6-03fe525ec875.jpg)

**Comment by deathlyrage** [comment]
Please learn how to spell correctly. "incrimental" can't possibly be right.

**Comment by YautjaFett** [comment]
You called it, fixed.  Also Mar informed me of making sure that I can recreate bugs before posting them here.

**Comment by YautjaFett** [comment]
Circle, Jina and I tested this as adults and babies and we positive it's not the game breaking bug it looked like.
