### ISSUE TITLE
Ankylosaurus laying down sound loop

### ISSUE THREAD

**Issue by AroraTitania** [deathlyrage/theisle-bugs#241]
Patch: 4628
Server: NY3 Official

After laying down as an Anky adult or hatchling there is a constant loop sound of the laying down sound. It only stops after standing up and will start everytime you lay down again.

https://youtu.be/QEwTvfNvK2Y

https://youtu.be/tgM1bU7fs3c

**Comment by dinosauriac** [comment]
Like I said previously, this is not a bug. It is the sound of your tail scraping back and forth along the ground. Put your camera next to the tail to better understand.

**Comment by AroraTitania** [comment]
Alright then, my bad!
