### ISSUE TITLE
Herra's teeth & head spines grow bigger depending on the camera angle.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#242]
Patch: 4628
Server: NY8 Official
Depending on the camera angle, herrera's teeth and head spines grow bigger.
When zoomed in they go back to their normal size.
https://youtu.be/Wf3556LvT2c

**Comment by Paleocolour** [comment]
Should be fixed.

**Comment by oOCircleofLifeOo** [comment]
Fixed with Patch .4637
