### ISSUE TITLE
(V3) Black grass is sideways

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#244]
Patch: 4628
Server: NY8
Found a patch of black grass propped up sideways on V3 here:

![black foliage sitting sideways coord](https://user-images.githubusercontent.com/32628229/32027557-9491a8e0-b99e-11e7-9d0c-4c6f8191b002.jpg)
![black foliage sitting sideways](https://user-images.githubusercontent.com/32628229/32027567-9c6fa742-b99e-11e7-846f-2d37223ed2f2.jpg)
Logging out didn't get rid of it and I doubled back with another dino to confirm:

![black foliage sitting sideways confirmed](https://user-images.githubusercontent.com/32628229/32027584-b33bc42e-b99e-11e7-9be0-704ab6ba7d78.png)
![sideways grass](https://user-images.githubusercontent.com/32628229/32098609-1b9b7360-bac2-11e7-8170-0c705ad46d6a.jpg)
![grass 2](https://user-images.githubusercontent.com/32628229/32098611-1fb2dcea-bac2-11e7-86ae-d0ad74752b3c.jpg)
![grass 3](https://user-images.githubusercontent.com/32628229/32098616-21c99352-bac2-11e7-8383-2b7cce19d95a.jpg)

Along most of the mountainsides along this shore, the grass sits at the angle of the wall but is away from it.
![grass offset from the wall](https://user-images.githubusercontent.com/32628229/32098762-95ecacd8-bac2-11e7-968d-a1b3c969268d.jpg)

**Comment by Paleocolour** [comment]
This bug  is difficult to fix because of the way grasstypes work. I think there will always be a few not correctly aligned to the normal of the landscape. If there is an especially bad area where a lot of grass is placed this way, I could look at it, but if we try and fix every last one it's going to be a huge time sink for relatively little gain.

**Comment by YautjaFett** [comment]
Understood, I just save the smaller stuff in case it's asked for and just report the larger items. Thanks Paleo

**Comment by Hypno123** [comment]
Map no longer in development.
