### ISSUE TITLE
Pachy's teeth grow depending on camera angle.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#245]
Patch: 4633
Server: NY8 Official
Depending on the camera angle, pachy's teeth grow.
This doesn't happen when zoomed in.
Related issue to #242 and #243 
![20171026093024_1](https://user-images.githubusercontent.com/30121219/32045360-f7f33040-ba37-11e7-885e-cb83ed6e4859.jpg)

**Comment by Paleocolour** [comment]
This should be fixed now.

**Comment by oOCircleofLifeOo** [comment]
fixed with patch .4637
