### ISSUE TITLE
(V3) Ocean not blending correctly with land.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#247]
Patch: 4634
Server: NY8 Official
Ocean water is not blending correctly with the coastline, being too elevated compared to land, making it float.
![20171026142900_1](https://user-images.githubusercontent.com/30121219/32055811-c43b2528-ba5a-11e7-93e0-29957558f0c0.jpg)
![20171026144212_1](https://user-images.githubusercontent.com/30121219/32056194-e896c502-ba5b-11e7-903c-1f0555de3d22.jpg)

Map Location:
![20171026143057_1](https://user-images.githubusercontent.com/30121219/32056336-4df7db84-ba5c-11e7-8038-252069838acd.jpg)

**Comment by oOCircleofLifeOo** [comment]
Here´s a Vidoe of it. It´s kinda hard to see in 2D pics for me. https://www.dropbox.com/s/2uuq6yw29smxqqh/2017-10-26%2015-48-50.mp4?dl=0

**Comment by YautjaFett** [comment]
Patch 1.28.4635
Server NY8
Another spot where the water isn't blending properly on land:
![water not blending](https://user-images.githubusercontent.com/32628229/32076198-f82a0ed2-ba53-11e7-9b7e-f04ae30403a7.jpg)

**Comment by YautjaFett** [comment]
Patch 4636
Server NY8
Found another spot further down the coast from Mar's original coast:
![water not blending 3 coords](https://user-images.githubusercontent.com/32628229/32129552-b1001fe8-bb3d-11e7-9668-5d265b0edabd.png)

**Comment by Paleocolour** [comment]
All have been fixed. Please test in the next build.

**Comment by MarianaBoni** [comment]
On the place I've mentioned, there's still a bit not completely blended.
![20171029172310_1](https://user-images.githubusercontent.com/30121219/32146364-3bcca3e4-bcce-11e7-9f38-346deb786fb2.jpg)
![20171029172319_1](https://user-images.githubusercontent.com/30121219/32146367-42815d60-bcce-11e7-8cc6-ae025b7f648f.jpg)

**Comment by YautjaFett** [comment]
Patch 4645
Server NY8
The area in the original post looks fixed.  On the way there, I spotted a little one.  It's in a V shape and blends well with the shape of the shore in that area:
![247](https://user-images.githubusercontent.com/32628229/32213810-02683c32-bdda-11e7-937e-d1a4f7a33375.jpg)
![32076198-f82a0ed2-ba53-11e7-9b7e-f04ae30403a7](https://user-images.githubusercontent.com/32628229/32213923-74b9a866-bdda-11e7-9682-da308cb926ec.jpg)

**Comment by Hypno123** [comment]
Map no longer in development.
