### ISSUE TITLE
(V3) Patch of Grass and flowers in centre lake

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#248]
Gameversion: 4634 (Dev Branch)
Server: NY8

In the middle of centre lake is a patch of grass and flowers.
![20171026155532_1](https://user-images.githubusercontent.com/28966884/32057240-f1dd4496-ba66-11e7-9ba0-91997af197dc.jpg)

![v3 map centre lake](https://user-images.githubusercontent.com/28966884/32057184-c9183372-ba66-11e7-8d18-998fbdbeafe4.jpg)

**Comment by YautjaFett** [comment]
Patch 4636
Server NY8
Found a tree in this lake, (there are more just to the right outside the screenshot).
![tree in the lake a few more next to this one](https://user-images.githubusercontent.com/32628229/32098888-ffd1a31a-bac2-11e7-8a3d-83e8b9581c6c.jpg)
