### ISSUE TITLE
(V3) Visibility changes depending on how deep the lake is.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#253]
Patch: 4636
Server: NY8 Official
Depending on how deep the camera is inside a lake, the visibility changes.
Example 1:
Upper Part:
![20171027171220_1](https://user-images.githubusercontent.com/30121219/32123355-c63e9c40-bb5b-11e7-98e1-c11e88b68de5.jpg)
Deeper Part:
![20171027171213_1](https://user-images.githubusercontent.com/30121219/32123322-a14277cc-bb5b-11e7-9272-79ef0e984d96.jpg)

Example2:
Upper Part:
![20171027211005_1](https://user-images.githubusercontent.com/30121219/32123332-aa37c03a-bb5b-11e7-9194-38c2495d59dc.jpg)
Deeper Part:
![20171027211002_1](https://user-images.githubusercontent.com/30121219/32123337-b04be56e-bb5b-11e7-97d3-44f5e2f570bd.jpg)

**Comment by Paleocolour** [comment]
This is a matter of extending the volume down, should be an easy fix.

**Comment by YautjaFett** [comment]
Patch 4637
Server NY8
Some of the lakes still have this in the deepest areas.  

![desktop screenshot 2017 10 28 - 21 25 59 23](https://user-images.githubusercontent.com/32628229/32140682-de273242-bc26-11e7-98c4-8982cc7615c6.png)
![desktop screenshot 2017 10 28 - 21 26 10 37](https://user-images.githubusercontent.com/32628229/32140684-dfe655e0-bc26-11e7-882a-246ad0857324.png)

**Comment by MarianaBoni** [comment]
Lakes where this issue is still present on 4639:
![v3map](https://user-images.githubusercontent.com/30121219/32142444-2f43e162-bc8f-11e7-8438-300ca51592d1.png)

**Comment by Paleocolour** [comment]
I've fixed those last three lakes I overlooked.

**Comment by YautjaFett** [comment]
Patch 4645
Server NY8
Lakes look good, visibility is consistent.
