### ISSUE TITLE
(V3) Invisible Wall Offshore

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#254]
If you go out past coordinates: -625,107.125, 103,127.281 facing away from land, turn around and try to go back to the shore, there is an invisible wall that anything Carno and bigger gets stuck in.  
https://youtu.be/R87Kg4WD3AA
![stuck offshore](https://user-images.githubusercontent.com/32628229/32140292-f7186450-bc18-11e7-92b4-d23c45344254.jpg)
There is a spot here where the water is about knee high for a Carno, That's the area where I was getting stuck.

**Comment by Paleocolour** [comment]
Can you create a picture of the point on the V3 map where this occurs? I can't use the in-game coordinates very well in-editor.

**Comment by Paleocolour** [comment]
I can't reproduce this as of 4652.

**Comment by Paleocolour** [comment]
@YautjaFett please try and reproduce this on the latest patch. if you cannot reproduce it, mark it as closed.

**Comment by YautjaFett** [comment]
@paleocolour I went as a Velo, showed Punch where it was and saw him not get stuck.  This looks like it's been taken care of.
