### ISSUE TITLE
(V3) Harsh looking hill.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#255]
Patch:
Server: NY8 Official
Harsh looking hill near the coastline.
![20171028105944_1](https://user-images.githubusercontent.com/30121219/32133467-3401f438-bbd0-11e7-9d9f-3b7483eaab27.jpg)
![20171028105954_1](https://user-images.githubusercontent.com/30121219/32133469-3a9d1a02-bbd0-11e7-8e89-476879b46964.jpg)
![20171028110630_1](https://user-images.githubusercontent.com/30121219/32133471-3d64b916-bbd0-11e7-8f1c-ccea35983ad8.jpg)

**Comment by YautjaFett** [comment]
Patch 4637 
Fixed.
