### ISSUE TITLE
Movement slide when turning.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#257]
Patch: 4643
Server: NY8 Official and Hosted Server
When turning, your character slides, almost as if alt turning.
It also appears to have the effect of an invisible wall.
Made two videos, on different servers to be sure it wasn't a lag issue.
https://youtu.be/Owteqsk2Nk0
https://youtu.be/I5Sr21oPAe4

**Comment by Hypno123** [comment]
The slide while turning is no longer apparent.
