### ISSUE TITLE
(V3) Trees growing on salt water and sand.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#262]
Patch: 4644
Server: NY8 Official
Trees unrealistically growing on salt water and sand.
![20171029160936_1](https://user-images.githubusercontent.com/30121219/32146185-5a7f5a1e-bccb-11e7-82ac-76a59f84262f.jpg)
![20171029161211_1](https://user-images.githubusercontent.com/30121219/32146189-62c80572-bccb-11e7-82de-6877145cf6be.jpg)
![20171029172914_1](https://user-images.githubusercontent.com/30121219/32146393-b6b6b608-bcce-11e7-8fa2-fb6444259313.jpg)
![v3map](https://user-images.githubusercontent.com/30121219/32146446-8ad3a95a-bccf-11e7-9666-71253a9350f0.png)

**Comment by Hypno123** [comment]
Map no longer in development.
