### ISSUE TITLE
Baryonyx has a hole on his underbelly

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#263]
Bary has an open slit seen here:
Example:
![desktop screenshot 2017 10 29 - 11 18 34 47](https://user-images.githubusercontent.com/32628229/32146890-4c3b4cfe-bc9b-11e7-9756-649d968666d8.png)

**Comment by Paleocolour** [comment]
Related to bug #260 
LODs and 2UVs need to be redone by Jake for this dinosaur as the incorrect mesh was used when creating them.

**Comment by Paleocolour** [comment]
should be fixed in next patch

**Comment by oOCircleofLifeOo** [comment]
Fixed in Patch .4652!
