### ISSUE TITLE
Dinosaurs stutter/slide after eating & drinking.

### ISSUE THREAD

**Issue by Punchpacket** [deathlyrage/theisle-bugs#268]
**Patch:** 4645
**Server:** NY8 Official
After the eating/drinking animation finishes so that you're able to move away from the plant/carcass/water you'll begin to slide and stutter around that general area for a short period of time.
https://www.youtube.com/watch?v=q9-YuGVTMU4&feature=youtu.be

**Comment by MarianaBoni** [comment]
This issue is not related to eating/drinking. It's the new movement mentioned on the issue #257
