### ISSUE TITLE
(V3) Slight gap in the map at the bottom of a lake.

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#269]
Patch 4645
Server NY8
At the bottom of the lake near coordinates, -45, 590, there is a small "slit" in the map.
![desktop screenshot 2017 10 31 - 02 39 12 72](https://user-images.githubusercontent.com/32628229/32218039-edea0724-bde6-11e7-96b9-fc21d9911bcd.png)
![slit in the map at the bottom of the lake](https://user-images.githubusercontent.com/32628229/32218054-f3bf28aa-bde6-11e7-8a28-0f34ac1ea848.jpg)

**Comment by Hypno123** [comment]
Map no longer in development.
