### ISSUE TITLE
Anky LOD Issue

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#271]
patch: 4649
Server: NY3
Description: Ankys textures flicker/change slightly when you attack. It only happens if you´re zoomed out fully. 
https://www.dropbox.com/s/rndva4vpf4rgw3v/2017-10-31%2003-27-10.mp4?dl=0
Steps to reproduce: Spawn as Anky -> look at it´s side -> zoom out fully -> press the attack button that swings your tail away from the camera -> the textures on its back will change for a split second.

**Comment by Paleocolour** [comment]
This should be fixed in the next patch. I made Anky LOD out at a further distance.

**Comment by oOCircleofLifeOo** [comment]
fixed in game version .4652! Thanks. This issue can be closed.
