### ISSUE TITLE
The Isle is unable to maximize with Task Manager "Always on Top"

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#272]
Patch 4649

When the Task Manager is open and "Always on Top" is checked, The Isle is unable to maximize while in fullscreen mode.  Multiple attempts to open The Isle result in a black screen and will eventually crash.  The second time I duplicated this, I got the "failed to read memory" error.
Example:
https://youtu.be/tN0AOxcMtrM

Steps to Reproduce:
1.  Run TheIsle.exe in fullscreen mode.
2.  Start the Task Manager and make sure "Always on Top" is checked.
3.  Attempt to maximize The Isle until crash occurs.

**Comment by MarianaBoni** [comment]
Not a bug. You need to do a bit of troubleshooting, since it's on your end.
Just tried it and worked fine https://www.youtube.com/watch?v=xzueLdtTZ2o&feature=youtu.be

**Comment by YautjaFett** [comment]
How odd, I'll look into why this happened for me. Thank you
