### ISSUE TITLE
(V3) Swimming elevation changes depending on the depth of the water

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#276]
Patch 4653
Server NY3 Official
Swimming elevation changes depending on the depth of the water you´re in.
Video: https://www.youtube.com/watch?v=btF3-yEJSzQ

Steps to reproduce:
1. Select a dinosaur and spawn on the V3 Map -> find a Lake (freshwater not saltwater)
2. Swimm in a shallow part of the lake. Your dino will be submerged about half.
3. Swimm into a deeper part of the lake. Your dino will sink till it´s nearly fully submerged.

While swimming in saltwater this also occurs but not to that extreme. Even in very deep water your swimming elevation stays like this:
![20171102213813_1](https://user-images.githubusercontent.com/28966884/32349327-fc93eaba-c016-11e7-98e8-bce113f65405.jpg)
Video: https://www.youtube.com/watch?v=jkOuteBlqng&feature=youtu.be

Only tested with Maia and in one lake so far. 
![v3 map swimming elevation maia 4653](https://user-images.githubusercontent.com/28966884/32349209-8a2a52ca-c016-11e7-8ff8-8a1c324f1218.jpg)
Will provide a list with more specis and lakes here soon:

Oro: Can walk into the water very far and will swim fully submerged the whole time. No noticable sinking or elevation while swimming. Video: https://www.youtube.com/watch?v=F3w7TA4dZu4

Taco: Same issues as maia. Will start to sink dependent on how deep the water gets. Video: https://www.youtube.com/watch?v=hCJyxyDUjeE

Velo: looking good. No sinking, good swimming elevation. Working as intended?
https://youtu.be/4yvq9ui9Cas

**Comment by Hypno123** [comment]
Map no longer in development.
