### ISSUE TITLE
(New Eating/Drinking System) Eating/Drinking animations replace idle 

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#282]
Patch 4690
Server NY8

To the player, eating/drinking animations stop when the action is stopped, to surrounding players, they will appear to be eating/drinking instead of showing the idle animation.  This only happens to the **Acrocanthosaurus** and the **Ankylosaurus**.  

Steps to reproduce:
1. Eat/Drink

Example:  
This was the view from my screen playing as the **Acro**:
![acro says everything is fine](https://user-images.githubusercontent.com/32628229/32484114-9335a334-c353-11e7-83b2-407d84bef7f7.png)

and this was the view from oOCircleofLifeOo:
https://youtu.be/oW7YTMCHHTQ

Here is an example of the **Anky** showing the same behavior:
https://youtu.be/fyY4AXmeZuU

**Comment by deathlyrage** [comment]
Fixed in 4765

**Comment by oOCircleofLifeOo** [comment]
can confirm. fixed in .4765
