### ISSUE TITLE
(New Eating/Drinking System) Tyrannosaurus and Rex_Adult get stuck in animation loop when drinking

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#284]
Patch 4690

**Tyrannosaurus** and **Rex_Adult** both get stuck in the drinking animation loop when they take a drink.  Relogging is the only way to stop once this is started.  

**Tyrannosaurus** also _drinks corpses_ instead of eating them, (refer to issue #291).   **Rex_Adult's** eating animation is just fine.

**Example:**
https://youtu.be/rSmxefBgjmM

**Comment by AroraTitania** [comment]
Video isn't playing.

Tyrannosaur getting stuck in drinking loop:
https://www.youtube.com/watch?v=NapfUIdkDPg

Tyrannosaur doing the drinking animation while eating:
https://www.youtube.com/watch?v=hgh-Rxra6bo

**Comment by YautjaFett** [comment]
I may have turned my computer off too early.  Thank you Arora!

**Comment by dinosauriac** [comment]
That's a weird one. The animation montage is set up the same as all the others, not sure why it would misbehave.

**Comment by deathlyrage** [comment]
Fixed in 4762

**Comment by oOCircleofLifeOo** [comment]
Can confirm it´s fixed in 4762.
