### ISSUE TITLE
(New Eating/Drinking System)  Holding E continues animation loop, but only replenishes a small amount of hunger/thirst once

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#286]
Patch .4690
Server NY8
Subject: New eating/drinking system
Video: https://youtu.be/_UiS9M9LgBk
Summary: Pressing **E** once triggers one animation loop but doesn´t make you gain any hunger/thirst.  Holding **E**: The animation loop starts to play, grants you a bite/sip after a few seconds of holding E (Video Timestamp: 0:06) and then it continues without any further effect/gain of resource.
This happens for all species drinking and eating (exception: Austros food gain while eating).

Steps to reproduce:
1. Select any dinosaur (not austro), spawn and find water/food.
2. Aim your Head at the ressource and press E once. One animation loop plays but you don´t gain any food/water.
3. Now press and hold E. The animation loop starts, you gain one bite/sip of food/thirst and then it continues without any further effect.

The only exception is the Austro right now. Instead of just gaining a small amount of food, Austro instantly fills all his hunger (starting at 32 hunger, gaining 33 Food value) with the first bite.
https://youtu.be/ahtpw_eYIr4

**Comment by AroraTitania** [comment]
Video isn't playing.

Tyrannosaur getting stuck in drinking loop:
https://www.youtube.com/watch?v=NapfUIdkDPg

Tyrannosaur doing the drinking animation while eating:
https://www.youtube.com/watch?v=hgh-Rxra6bo

**Comment by YautjaFett** [comment]
*Video has finished uploading.

**Comment by deathlyrage** [comment]
Intended Functionality. Letting go of E is a cancel and you are giving up further gains.

**Comment by oOCircleofLifeOo** [comment]
Fixed in patch .4737. Dinosaurs now gain food/water over time while holding E on the ressource.
