### ISSUE TITLE
Tyrannosaurus drinks from corpses.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#291]
Patch: 4691
Server: Hosted
Tyrannosaurus is using its drinking animation for eating. (Not to be confused with RexAdult, which is using the correct animations).
https://youtu.be/_64hUwlPr-M

**Comment by AroraTitania** [comment]
Already reported in issue #284

**Comment by MarianaBoni** [comment]
Didn't see because it isn't a separate issue, like it was mentioned before to be done.

**Comment by YautjaFett** [comment]
Apologies Mar, you're right.  I must have been tired last night, they seemed like close enough related issues.

**Comment by dinosauriac** [comment]
This dinosaur technically doesn't exist anymore, it's not intended to really be used and is likely to be replaced. That said, it's a quick fix provided this still shares the same skeleton as the normal T.Rex.
