### ISSUE TITLE
(New Eating/Drinking System) Dryo drinking loop animation issue

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#293]
Patch: .4691
Server: Hosten and NY8
Video: https://www.youtube.com/watch?v=NbDbiAONR98
Summary: Dryos tip of the tail skips while in the transition between two animation loops (Video Timestamp 0:10).
Steps to reproduce:
1. Select and spawn as a Dryo.
2. Find a watersource, press and hold E on it.
3. Watch the tip of the tail skip it´s position when one drinking animation loop is ending and the next one is starting.

**Comment by dinosauriac** [comment]
Fixed in revision 4759
