### ISSUE TITLE
(New Eating/Drinking System) Getting stuck while eating when the corpse turns into Goremesh

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#296]
Patch: .4691
Server: NY8
Video: https://www.youtube.com/watch?v=Kz-E001fo1Q

Summary: Every carnivores get stuck completely (not able to turn or move in any way) when they eat a corpse and it turns into a goremesh (Video Timestamp: 1:26). Only a relog fixes this issue.

Steps to reproduce:
1. Select any Dino (Example: Austro), kill it and return as a carnivore (Example: Herrera).
2. Start eating the corpse (press and hold E for a few seconds, let go and start over again, so it actually takes away food value form the corpse) and continue that till the corpse turns into a Gore mesh. 
3. You will find yourself stuck in the Idle animation unable to move till you relog.

**Comment by MarianaBoni** [comment]
This also happens with species who don't leave a goremesh.

**Comment by deathlyrage** [comment]
Fixed in 4729

**Comment by MarianaBoni** [comment]
Not fixed on 4733
