### ISSUE TITLE
Pressing "A" and "S" or "A" and "D" prevents you from performing certain calls

### ISSUE THREAD

**Issue by oOCircleofLifeOo** [deathlyrage/theisle-bugs#300]
Patch: .4691
Server: NY8
Video: https://youtu.be/kYEpcu4eKZI
Summary: If you move diagonal with any species (Pressing "A" and "S" or "S" and "D" simultaneously)  you cant use the following calls:
AS: 1 (broadcast) and 2 call (friendly)
DS: 2 (friendly) and 3 call (threaten)

Thanks goes to Meliora, who found and reported this bug.

**Comment by MarianaBoni** [comment]
This has been mentioned days ago to not be a relevant issue to be mentioned.
