### ISSUE TITLE
(New Eating/Drinking System)  Dinos are able to jump while eating or drinking

### ISSUE THREAD

**Issue by YautjaFett** [deathlyrage/theisle-bugs#305]
Patch 4703
Server NY8

Dinosaurs that can **jump** are able to do so while **eating/drinking**.
**Example:**  https://youtu.be/gB7nxNFU-VU

Steps to Reproduce:
1.  Press **E** to begin the _eating/drinking_ animation loop.

2.  Once the animation loop has started, let go of **E** and press **jump**.

3.  While  in air, hold **E** to continue the _eating/drinking_ animation loop.

4.  Now you are able to **jump** until your stamina depletes while _eating/drinking_.

**Comment by deathlyrage** [comment]
Fixed in 4728
