### ISSUE TITLE
Family icons still showing after dying.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#309]
Patch: 4755
Server: NY8 Official
After dying, the parent/descendant icons were still visible. 
Relogging fixed this issue.
Image shows myself standing next to my former body:
![20171113195718_1](https://user-images.githubusercontent.com/30121219/32748140-40eaf16e-c8b3-11e7-8585-744c94f2e0cb.jpg)
After relogging:
![20171113195926_1](https://user-images.githubusercontent.com/30121219/32748181-5c8ec8be-c8b3-11e7-9ee5-f1c444749126.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4773

**Comment by MarianaBoni** [comment]
Can't be verified completely because NY8 has global tags enabled, so they override family icons.
Will verify if fixed when they're disabled or other servers that are viable are on patch 73+

**Comment by MarianaBoni** [comment]
Can not be verified on Patch 4775 because family icons are missing (issue #316 ). Will verify it when fixed.
