### ISSUE TITLE
Growth not saving.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#313]
Patch: 4773
Server: NY6 Official
After growing from juvenile to adult, relogging resets your growth, sending you back to juvenile and to the place you first spawned in.
This also happens when you're per example dinosaur x, get nested as dinosaur y, if you relog you'll be back to dinosaur x.
Reset seems to happen when changing blueprints, not resetting when you're on growth example 0.2 to 0.3, but from juvenile to sub/adult.
This happens with all species, both on survival and progression when nested.
https://youtu.be/bf3gsFWdigE

**Comment by deathlyrage** [comment]
Fixed in 4788
