### ISSUE TITLE
Nest duplicating possible after relog

### ISSUE THREAD

**Issue by 0ida** [deathlyrage/theisle-bugs#315]
Patch: 4773 and 4775 - 2296374 dev branch
Server: NY3 Official/ Dev 8-

When placing a nest you can place a new one immediately if you relog. Each Nest gets its own ID.
In the Database it raises the number of nests for each duplicate you place under sqlite_sequence, but in the table "Nests" there is only one Nest with the newest NestUID shown. When the server restarts, only the newest nest remains

Video Example from the Official NY3 Server:
https://youtu.be/CzXGdxm7Xag

**Comment by deathlyrage** [comment]
Fixed in 4780

**Comment by deathlyrage** [comment]
Fixed in 4787
