### ISSUE TITLE
Growth Button assuming Progression timer on Survival Mode.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#323]
Patch: 4792
Server: NY6 Official
On the Survival Mode, if you open the Esc Menu where it shows your Growth, and wait the same amount of time you do when waiting for the Progression timer on Progression servers (45 seconds), the button will light up and not show your growth anymore.
By pressing the growth button, nothing will happen and the Esc Menu will close.
https://youtu.be/ZmpKTUL_O0s

**Comment by deathlyrage** [comment]
Fixed in 4847
