### ISSUE TITLE
Nested Utahs grow to its old size.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#325]
Patch: 4792
Server: NY6 Official
Nested Utahs still grow to its old size before it was resized (bigger).
Adult Utah also only reaches 0.8 on survival while Adult Carno and Adult Rex reach 1.0
Nested Utah on the left:
![20171120175436_1](https://user-images.githubusercontent.com/30121219/33033456-5206f36c-ce1c-11e7-8b5e-fbaa4594d1ce.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4849

**Comment by MarianaBoni** [comment]
Not able to see if it's fixed because nesting doesn't work, as seen on #333
