### ISSUE TITLE
[Dev Kit] Hatchling and Juvenile Utah missing their skin

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#326]
Dev Kit - Development Branch
Both Hatchling and Juvenile Utah are missing their skin.
![hatchling](https://user-images.githubusercontent.com/30121219/33035296-8253521c-ce22-11e7-9519-f13794d97c19.png)
![juvenile](https://user-images.githubusercontent.com/30121219/33035317-92943038-ce22-11e7-8e99-6f4ddd18bfc6.png)

**Comment by Paleocolour** [comment]
This happens because the Materials and Textures for those two are still in the PrivateContent folder. If this is being pushed to public now, it should be merged with TheIsle folder.

**Comment by deathlyrage** [comment]
@Paleocolour please move it to the non-private content folder.

**Comment by deathlyrage** [comment]
Fixed a while back on dev kit dev branch.
