### ISSUE TITLE
(UI) PlayerList not lined up.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#327]
Patch: 4795
On playerlist UI, the categories (Name, Options, Unique ID and Ping aren't lined up.
Player and Options sections aren't the same vertical size as Unique ID and Ping, making the usernames not fit correctly on the Player boxes.
![20171121093025_1](https://user-images.githubusercontent.com/30121219/33064647-58bab040-ce9e-11e7-9de1-9c1eacff8cd8.jpg)

Resolution Settings:
![20171121094129_1](https://user-images.githubusercontent.com/30121219/33064664-638f05e8-ce9e-11e7-8e48-3f755a9cac4d.jpg)

**Comment by dinosauriac** [comment]
Should be fixed as of revision 4796
