### ISSUE TITLE
(UI) Servers' information not lined up/cut off.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#328]
Patch: 4797
The information for the sections Players, Game Mode, Map, Version and Ping aren't lined with their respective columns.
![20171121135717_1](https://user-images.githubusercontent.com/30121219/33076818-bf200db8-cec5-11e7-9693-a847efae5e39.jpg)

**Comment by dinosauriac** [comment]
Just committed a potential fix for this in version 4798, I can't really test it locally since any servers I put up using the editor don't seem to show on the list.

**Comment by MarianaBoni** [comment]
It has been fixed on 98.
![20171121200126_1](https://user-images.githubusercontent.com/30121219/33095779-bad45f16-cefc-11e7-9fb7-cbba1a646e01.jpg)
