### ISSUE TITLE
(UI) Main Menu buttons not interact-able before a button is pressed.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#329]
Patch: 4798
After launching the game, the main menu button aren't interact-able (hovering over them has no reaction) if a player doesn't click somewhere randomly first.
This also happens after leaving a server.
https://youtu.be/lg9Pa0Fdhu8

**Comment by dinosauriac** [comment]
I've forced the main menu bar to be auto-focused upon opening, which seems to have fixed this. You'll still get the momentary lag while the background map loads but it should be interactable without needing an extra click now.
