### ISSUE TITLE
Death screen showing stats and chat behind it.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#331]
Patch: 4798
When a player dies and the Death UI appears, Chat Box, Stats UI and other information show behind it.
![20171121221858_1](https://user-images.githubusercontent.com/30121219/33100019-cde36b16-cf0a-11e7-82a2-0188aa0fa1b3.jpg)

**Comment by dinosauriac** [comment]
@deathlyrage found a simple way to do this, but it needs to be set in the player controller to work. Tested it out in a locally hosted game with multiple sessions running, works flawlessly so far. 

![hide hud on death](https://user-images.githubusercontent.com/18335743/33345226-96c1a0ac-d483-11e7-809d-5489393ba7db.jpg)

**Comment by MarianaBoni** [comment]
Fixed on patch 4827
