### ISSUE TITLE
(UI) Unreadable Server Filters.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#332]
Patch: 4798
On the Server List, the Server Filters' font is white on a yellow background, making it really difficult to read.
![20171121215657_1](https://user-images.githubusercontent.com/30121219/33101248-73327e6e-cf0f-11e7-8e4b-f7ee2f1659ad.jpg)

**Comment by dinosauriac** [comment]
Changed the selected button to be a bit more subtle, should be a lot easier to read now. Hopefully it still looks okay.

**Comment by MarianaBoni** [comment]
Looks much better now
![20171122094328_1](https://user-images.githubusercontent.com/30121219/33119783-f231c564-cf67-11e7-9464-dfc1c806ac4f.jpg)
