### ISSUE TITLE
(UI) White UI background on windowed mode.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#334]
Patch: 4803
When your game is set to Windowed mode, when you move its window, the background of all transparent UI sets will change to white. Once you stop moving the window and let the click go, it turns normal again.
https://www.youtube.com/watch?v=GbM6azZUEQQ

**Comment by dinosauriac** [comment]
We pretty much agreed this is an edge case most users wouldn't encounter, and since it sorts itself out if you're not dragging the screen around constantly it doesn't seem like a serious issue.
