### ISSUE TITLE
Main Menu Patch/Game Version outside of respective box.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#335]
Patch: 4825
The Patch/Game Version number on the Main Menu is outside of its respective box.
![20171127163125_1](https://user-images.githubusercontent.com/30121219/33279598-02e6d042-d397-11e7-930e-8772c039bf26.jpg)

**Comment by dinosauriac** [comment]
I think this is only an issue on development builds, normal version numbers aren't fifteen digits long.

**Comment by MarianaBoni** [comment]
On patch 4827:
![20171130114821_1](https://user-images.githubusercontent.com/30121219/33429578-51282064-d5c5-11e7-8cae-5934d406b089.jpg)

**Comment by MarianaBoni** [comment]
This has been fixed with the new main menu UI layout as seen here:
![20171202120102_1](https://user-images.githubusercontent.com/30121219/33515254-88f44470-d758-11e7-98fa-c811dc202ad1.jpg)
