### ISSUE TITLE
Pressing "Esc" will close the Death screen.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#336]
Patch: 4825
Server: NY8 Official
After dying, if the player presses "Esc" while on the Death screen, the Death screen will disappear and it's possible to interact with the Esc Menu.
https://youtu.be/UYQTCGpZ1fY

**Comment by dinosauriac** [comment]
I think this is one @deathlyrage will have to sort out.

**Comment by deathlyrage** [comment]
Fixed in 4850
