### ISSUE TITLE
Missing translations.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#338]
Patch: 4834
Some translations are missing.
These are from the Portuguese Localization 1.3, on dev branch. Also missing on others.
Nest Information
![20171202115925_1](https://user-images.githubusercontent.com/30121219/33515265-c624ff1a-d758-11e7-8783-68fe2d27ae92.jpg)

Settings
![20171202115832_1](https://user-images.githubusercontent.com/30121219/33515268-cb674582-d758-11e7-8453-47c7e941215d.jpg)
![20171202115503_1](https://user-images.githubusercontent.com/30121219/33515284-e790dd54-d758-11e7-9f35-344a5e90c9bc.jpg)
![20171202115509_1](https://user-images.githubusercontent.com/30121219/33515285-eada04e0-d758-11e7-86df-846bdb684423.jpg)

Hosting (Game modes and settings)
![20171202115417_1](https://user-images.githubusercontent.com/30121219/33515289-0566afa2-d759-11e7-902a-65495fd1c3f8.jpg)
![20171202115414_1](https://user-images.githubusercontent.com/30121219/33515294-10bcbd9c-d759-11e7-8ee6-d04e07a89e82.jpg)

Progression menu:
![20171202115604_1](https://user-images.githubusercontent.com/30121219/33515301-22f13c68-d759-11e7-8d58-b46ba44cffe5.jpg)
![20171202115619_1](https://user-images.githubusercontent.com/30121219/33515302-25b51fe6-d759-11e7-8f2a-a6577d42ff1a.jpg)

Skin Select
![20171202115703_1](https://user-images.githubusercontent.com/30121219/33515308-2e971d26-d759-11e7-969c-9bb08ac62d41.jpg)

Enable/Disable on Mods Menu
![20171202115528_1](https://user-images.githubusercontent.com/30121219/33515311-436b6982-d759-11e7-99f3-b7bc5a4d0e34.jpg)

News
![20171202120102_1](https://user-images.githubusercontent.com/30121219/33515352-d360548a-d759-11e7-8074-1e6831660e3a.jpg)

**Comment by MarianaBoni** [comment]
Updated

**Comment by deathlyrage** [comment]
Partially Fixed in 5015
