### ISSUE TITLE
Interrogation Point showing two versions on Progression Screen.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#342]
Patch: 4836
The Interrogation point on the progression menu UI shows one version before any dinosaur being selected.
This version changes when a dinosaur is selected.
It shows rapidly when selecting any dinosaur the first time.
https://youtu.be/vlE63y5xFY0

**Comment by dinosauriac** [comment]
Huh, never head it called an "interrogation" point before. The button was missing the correct disabled image, should be fixed now.

**Comment by MarianaBoni** [comment]
Fixed on patch 4837
