### ISSUE TITLE
Players are able to hear chat beeping sounds from other chats.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#353]
Patch: 2538
Server: NY8
As any species, you're able to hear beeping sounds when people type in global chat, even if you aren't using global.
As the same species at a distance local is enabled, players are able to hear beeping sound from local while using other chats.
Players that are grouped, can hear group chat beeping sounds when using other chats.
Global Chat example:
https://youtu.be/MjeZm9idyn0

**Comment by deathlyrage** [comment]
Disabled chat beeps for the time being until its implemented better.

**Comment by deathlyrage** [comment]
Closing as chat beeps are disabled.
