### ISSUE TITLE
Scroll bars on MOTD aren't interact-able.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#356]
Patch: 5831
Server: Any with MOTD
The scroll bars on the MOTD aren't interact-able, making it impossible to read full messages.
![20171210005601_1](https://user-images.githubusercontent.com/30121219/33801005-1a2fbe14-dd45-11e7-9302-1f967953ef82.jpg)

**Comment by deathlyrage** [comment]
Fixed in 5010
