### ISSUE TITLE
Alberto shares the same chat as Rex.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#359]
Patch: 4873
Server: NY2 Official.
Albertosaurus shares the same chat as Rex, making it possible for players of both species to communicate in local chat.
Steps to reproduce:
- Player 1 chooses Alberto;
- Player 2 chooses Rex;
- Both players get at distance where local chat is visible
- Type in Chat.

**Comment by deathlyrage** [comment]
Fixed in 4912
