### ISSUE TITLE
Pressing "Confirm" without selecting a dinosaur will turn the screen black.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#361]
Patch: 4898
Server: NY8 Official/Hosted
When on the dinosaur selection menu (both sandbox and survival) if a player chooses a dinosaur, then goes back, and chooses the herbivore/carnivore faction again, the "confirm" button will be highlighted even without any dinosaur being selected. If the player presses confirm, it will send them to a black screen. UI sounds can still be heard in the background.
Steps to reproduce:
- Choose a sandbox or survival server;
- Choose herbivores/carnivores
- Select a dinosaur;
- Press Back;
- Choose herbivores/Carnivores again;
- Press Confirm.
Video: https://youtu.be/ch2Csd4P9Ig

**Comment by deathlyrage** [comment]
Fixed 4914
