### ISSUE TITLE
Server Login loading screens resolution issues.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#362]
Patch: 4925
Titles of on the server loading screen will be located under the text on some screen resolutions.
Steps to reproduce:
- Have your resolution set to x scale;
- Login to a server.

Example of the correct resize at 1920x1080:
![ae-bls-001](https://user-images.githubusercontent.com/30121219/34045899-fa3275fe-e1a2-11e7-9a53-f61e78f01113.png)

Example at 1366x768:
![ae-bls-045](https://user-images.githubusercontent.com/30121219/34045924-09f978b6-e1a3-11e7-8e11-fa18c171021e.png)

**Comment by deathlyrage** [comment]
Fixed in 5015
