### ISSUE TITLE
Theri is still using its old eating animation.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#363]
Patch: 4925
Server: NY8 Official
Therizinosaurus is still using its old eating animation (missing animation loops).
Steps to reproduce:
- Select Therizinosaurus on the dinosaur selection screen;
- Find a eatable bush and press E.
Video: https://youtu.be/oIWIzGftU9Y

**Comment by dinosauriac** [comment]
The plants in the testing level instantly vanish so this is difficult to quickly test, but it's been assigned the correct eating animation montage now so should hopefully be sorted out.

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
