### ISSUE TITLE
Invert X Axis Button stretches out when pressed/hovered.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#364]
Patch: 4960
When interacted with (pressed and hovered), when the Invert X Axis button on the Settings - Controls menu stretches. It only happens when selected (colored green).
Steps to reproduce:
- Launch the game;
- Go to Settings;
- Select Controls Menu;
- Press or Hover "Invert X Axis" Button.
Video: https://youtu.be/GJ_laorpmaw

**Comment by dinosauriac** [comment]
Should be resolved as of version 4977
