### ISSUE TITLE
Square Buttons on Settings menus missing sound.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#365]
Patch: 4960
The Square shaped buttons on all Settings menus are missing their sounds.
Steps to reproduce:
- Open the Settings UI;
- Interact with any square shaped button on any of these menus (Graphics, Gameplay, Controls).
Video showing the same buttons on the server list with sounds and the ones in settings without sounds: https://youtu.be/6plGKvUdVFU

**Comment by dinosauriac** [comment]
As of version 4977 all checkboxes in the settings menus should have interaction sounds. I'll be adding more sound to other objects (as I figure out how) over time. I actually just got the audio sliders to make beeps that reflect the volume level but I haven't got it working for every slider just yet.
