### ISSUE TITLE
Square shaped footprints.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#366]
Patch: 4960
Server: NY8 Official
Footprints are missing, appearing as a square shape.
Affected dinosaurs: Pachy, Theri, Acro, Alberto, Allo, Bary, Cerato, Dilo, Giga, Herra, MagnaRex, Spino, Sucho, Feathered Rex, Rex, Hypo Rex, Hypo Spino.
Steps to reproduce:
- Join a server;
- Select any of the above mentioned species;
- Walk/Trot/Sprint/Crouch.
Video: https://youtu.be/WZwA5D3rCKI

**Comment by dinosauriac** [comment]
We're reworking the step system currently, will be fixed once that's complete.

**Comment by Hypno123** [comment]
Footprints are correct shape and size.
