### ISSUE TITLE
Server Details of the selected server stay after refreshing the server list.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#369]
Patch:
When on the server list, if a player clicks on a server, it is highlighted as selected and the server details of that specific server will show on the "Server Details" tab.
After refreshing the page, the server isn't selected anymore, but the details for that server still show on the "Server Details" tab.
Steps to reproduce:
- Press Play;
- Select a server on the server list;
- Select "Server Details" tab;
- Refresh the server list.
Video: https://youtu.be/pyPfq47MJPY

**Comment by deathlyrage** [comment]
Fixed in 5009
