### ISSUE TITLE
(Nesting) Irregular point consuming, delay when adding points, etc

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#37]
- Adding food to the nest takes several seconds to process after you press the "+" button.
- Each egg used to need 15 food points (15minutes/nest points) to appear. Now per 15 food points you only get 1 nesting point.
- Nesting points sometimes disappear as well as the food placed on the nest.
- Nesting points seem to reset when there's no food on the nest after 1 tick.
- There is no option on the UI to be nested if you're on sandbox.

**Comment by deathlyrage** [comment]
All of these are intended except 15 food points. Fixed.
