### ISSUE TITLE
Duplicated Audio Quality settings.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#370]
Patch: 5018
(10/10) On the Audio Settings menu, the Audio Quality settings are duplicated. They appear duplicated with the original English version, and when using a translation, they appear with both English and the international version.
Steps to reproduce:
1) Launch the game;
2) Select Settings;
3) Select Audio;
4) Open Audio Quality settings.

English Version:
![20171220142006_1](https://user-images.githubusercontent.com/30121219/34211483-239e7a9a-e591-11e7-987a-c269e3f7853f.jpg)

International example Version:
![20171220135530_1](https://user-images.githubusercontent.com/30121219/34211503-2f41b006-e591-11e7-8965-702563ed1d8c.jpg)

**Comment by deathlyrage** [comment]
Fixed in 5021
