### ISSUE TITLE
Settings appear blank when changed to another translation.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#371]
Patch: 5018
(10/10) When changed to an international version, settings appear blank until selected.
Epic appears as Epic because it doesn't have a translation.
Steps to reproduce:
1) Change to another language (Right click The Isle in your Steam Library > Properties > Language);
2) Launch the Game;
3) Select Settings.
Video: https://youtu.be/SXk1Ycmt64w

**Comment by deathlyrage** [comment]
Fixed in 5091

**Comment by Hypno123** [comment]
Settings no longer appear blank.
