### ISSUE TITLE
Logged in during a server crash results in death on restart.

### ISSUE THREAD

**Issue by Punchpacket** [deathlyrage/theisle-bugs#377]
Patch: 0.1.33.5174
Server: US2 Official (All populated servers seem to be effected)
If you're logged into the server during a crash you'll find yourself dead upon server restart. I'd assume it may have something to do with the recent fix put in-place to prevent combat loggers.

Video: https://www.youtube.com/watch?v=O1ly4dnBEys&feature=youtu.be - Video has been edited/cut down in-order to save time.

**Comment by Hypno123** [comment]
Likely to be caused by the fix to #374

**Comment by deathlyrage** [comment]
Fixed
