### ISSUE TITLE
Feign limp not synced

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#378]
Patch: 5218
Server: Dev 8
Issue 1: Resting does not increase stamina regeneration - causes rex to not be able to gain stamina at all. (Effects all species.)
https://www.youtube.com/watch?v=9XRFWx6Cg3g

Issue 2: Resting does not increase bleed regeneration.
(Effects all species.)

Issue 3: Resting and feign limping is not synced between players - only shows animation locally. Real broken bone limp seems to be synced however.

https://www.youtube.com/watch?v=g_JvI8hXtKo
https://www.youtube.com/watch?v=gumMgErCGqQ

**Comment by deathlyrage** [comment]
Fixed in 5227

**Comment by Hypno123** [comment]
Stamina and bleed regeneration is now increased when resting.
Resting is now synced across players. 

Feign limping is still **not** synced in 5252.

**Comment by Hypno123** [comment]
Fixed.
