### ISSUE TITLE
Black screen when selecting species

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#379]
Patch: 5220
Server: Dev 8
Issue: Pressing confirm to select a dinosaur as it's rendering will result in a black screen.

To reproduce:

1. Select any dinosaur and wait for it to render until you can select confirm.
2. Select any other dinosaur.
3. Select confirm before the second dinosaur renders in.

(You can fix this issue manually by finding the back button.)

Video: https://www.youtube.com/watch?v=kfzP-C8dBPk

**Comment by dinosauriac** [comment]
Made a tweak regarding this in revision 5233, should hopefully be sorted now.

**Comment by Hypno123** [comment]
Fixed in 5233.
