### ISSUE TITLE
Missing sound when starving

### ISSUE THREAD

**Issue by Cocazou** [deathlyrage/theisle-bugs#380]
Patch: 5220
Server: Dev 8
Issue: The dino doesn't give a sound when he takes damage from starving.
Dino affected : 
-Galli
-Austro
-Velo
(probably each dino has this issue)

**Comment by deathlyrage** [comment]
Fixed in 5228

**Comment by Cocazou** [comment]
Confirming Fix

**Comment by Hypno123** [comment]
Damage sound now plays when starving/dehydrating.
