### ISSUE TITLE
Limping glide

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#381]
Patch: 5221
Server: Official US 1
Issue: Holding ALT while limping/feign limping will cause your dinosaur's limping animation to play slowly - this "glide" can only be seen locally.

https://www.youtube.com/watch?v=zf-vAMwZY94

**Comment by deathlyrage** [comment]
Fixed in 5227

**Comment by Hypno123** [comment]
Bug still apparent in 5252 - not fixed.

**Comment by Hypno123** [comment]
Fixed.
