### ISSUE TITLE
Humans face same direction

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#388]
Patch: 5252
Server: Dev 8
Issue: Players with human models face in the same direction as the local player when not moving.

To replicate:

1. Select human
2. Meet with another human
3. Ask them to not move
4. Begin facing in a different direction to them

Their character will begin to turn in the direction that your character is facing - this results in a 'jitter' bug when there are multiple players playing as a human.

Example of two humans: https://www.youtube.com/watch?v=_W-SrbO6e9c
Example of multiple humans: https://www.youtube.com/watch?v=gG4Uu8FBTdI

**Comment by deathlyrage** [comment]
Fixed in 5256

**Comment by Hypno123** [comment]
Tested with both two and multiple humans. Issue fixed.
