### ISSUE TITLE
Sub-rex short broadcast animation

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#389]
Patch: 5252
Server: Dev 8
Issue: Sub-rex broadcast animation is cut short - does not correspond with sound that is played.

Video: https://www.youtube.com/watch?v=Zd8DcSX3GyY

**Comment by dinosauriac** [comment]
Should be fixed as of revision 5314

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
