### ISSUE TITLE
Aiming down sights changes post processing effects

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#390]
Patch: 5252
Server: Dev 8
Issue: Aiming down the sight of your gun causes the gas mask tint effect to disappear.

Video: https://www.youtube.com/watch?v=9lqLQP3hiOg

**Comment by deathlyrage** [comment]
Issue 2 fixed in 5256

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
