### ISSUE TITLE
Humans blood camouflage

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#391]
Patch: 5252
Server: Dev 8
Issue: Humans are shown covered in blood when they step into a blood pool on the floor.

Edit: This also happens for footprints when stepped on.
Edit 2: This also happens for tribals.

Video: https://www.youtube.com/watch?v=0fLdK8joWtk

**Comment by dinosauriac** [comment]
The human character blueprint(s?) need their meshes set to not receive decals to fix this.

**Comment by deathlyrage** [comment]
Fixed in 5337

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
