### ISSUE TITLE
Humans cannot crouch, jump or sprint after pressing H or G

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#393]
Patch: 5252
Server: Dev 8
Issue: After pressing H or G as a human, you lose the ability to crouch, jump and sprint.

To replicate:

1. Select human
2. Press H or G
3. You will now not be able to crouch, jump and sprint until you press the button again.

Resting for dinosaurs is H
Feign limping for dinosaurs is G
^ Perhaps those are causing the issue?

**Comment by deathlyrage** [comment]
Should be fixed, Resting and Feign Limping is disabled for humans and tribals.

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
