### ISSUE TITLE
(Servers menu) Servers with a big name conceal the letters of the map/ping etc

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#40]
If servers have a big name, the letters get over the ones describing the map, ping, player number, 
![376210_screenshots_20170802153045_1](https://user-images.githubusercontent.com/30121219/28918272-910250f2-7840-11e7-9ae2-2aef2b93f6ec.jpg)

**Comment by deathlyrage** [comment]
Fixed in 4139
