### ISSUE TITLE
Nametags show at the players feet

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#414]
Patch: 5272
Server: Official US 4
Issue: Group nametags appear at the players feet for dinosaurs and mercenaries. Tribals are not affected by this bug.

![20180113200655_1](https://user-images.githubusercontent.com/30550499/34910286-8ccd798c-f8a9-11e7-84db-07602ec31c56.jpg)

**Comment by deathlyrage** [comment]
Fixed in 5328

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
