### ISSUE TITLE
Roaring does not show distant nametags

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#415]
Patch: 5272
Server: Personal testing server
Issue: Roaring as any dinosaur does not show nametags that are out of view distance, as it did before.

To replicate:

1. Select any dinosaur
2. Group with another player
3. Roar in an attempt to see each others nametag - it won't appear until you are closer to them.

**Comment by deathlyrage** [comment]
Intended Functionality.
