### ISSUE TITLE
Camara missing tail whip animation

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#417]
Patch: 5272
Server: Personal testing server
Issue: Camarasaurus currently has an 'invisible' tail whip attack. It damages other players but no animation is played.

Video: (Will get tomorrow - 4am as I write this.)

**Comment by dinosauriac** [comment]
Did a quick comparison between this and the way Puertasaurus is setup. Camarasaurus was missing any animation slot for its tail. As of rev. 5313 I've sorted that out, the tail whip appears to play and blend just fine now.

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
