### ISSUE TITLE
Typing in chat changes weapon

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#418]
Patch: 5315
Server: Dev 8
Issue: Typing the weapon change buttons (1, 3 or 4) while typing in chat will cause your weapon to change.

This is also a problem for tribals.

Video: https://www.youtube.com/watch?v=W0soAOnV4eo

**Comment by deathlyrage** [comment]
Fixed in 5316

**Comment by Hypno123** [comment]
Tested and fixed.
