### ISSUE TITLE
Dedicated Server language causes DB issues

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#421]
Patch: 5320
Server: Dedicated Servers
Issue: Tested with Windows server 2016. If you have your Windows server set to French, it causes database problems due to how they write decimals (this may affect more languages.) 

In English, we use a full stop (period: . ) to show decimal place.

![unknown](https://user-images.githubusercontent.com/30550499/34990740-1c39017e-fabf-11e7-89da-88133dcaadcf.png)

In French, they use a comma ( , ) to show decimal place.

![unknown 1](https://user-images.githubusercontent.com/30550499/34990744-215777da-fabf-11e7-9186-146fc1d1a9cf.png)

This can cause issues such as saving player location:

Windows server set as French and before logging out:

![unknown 2](https://user-images.githubusercontent.com/30550499/34990857-7af51860-fabf-11e7-93a5-59f1ec1f468f.png)

Windows server set as French and after logging out:

![unknown 3](https://user-images.githubusercontent.com/30550499/34990890-9b1448f0-fabf-11e7-8af5-217851450046.png)

**Comment by deathlyrage** [comment]
Fixed in 5327

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
