### ISSUE TITLE
Camara does not play roar animations

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#427]
Patch: 5347
Server: Personal test server
Issue: Camarasaurus' roar animations do not play when you press the corresponding buttons - this effects both client and server-side.

To replicate:

1. Go on sandbox
2. Select Camarasaurus
3. Press 1-4 and see no animation is played

**Comment by dinosauriac** [comment]
Found a minor oversight in the anim blueprint, this should be fixed in revision 5352.

**Comment by Hypno123** [comment]
Tested and confirmed fixed.
