### ISSUE TITLE
Chat UI enhancement

### ISSUE THREAD

**Issue by Hypno123** [deathlyrage/theisle-bugs#434]
Patch: 5358
Server: Any
Enhancement: Pressing the change chat channel buttons ([ or ]) should show the chat UI. 

Pressing these buttons currently doesn't make the UI visible, making it hard to tell when you change chat channels.

**Comment by deathlyrage** [comment]
Fixed in 5361

**Comment by Hypno123** [comment]
Tested and confirmed that it works correctly.
