### ISSUE TITLE
Species that can see under the map.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#46]
Species that can see under the map: Camara, Puerta, Acro, Allo, Cerato, Dilo
![20170804115034_1](https://user-images.githubusercontent.com/30121219/28966094-31a79456-790c-11e7-8dce-746f22602581.jpg)

**Comment by MarianaBoni** [comment]
Updated with the new species.

**Comment by Hypno123** [comment]
Fixed.
