### ISSUE TITLE
InGame Group problem with nesting

### ISSUE THREAD

**Issue by WunderWuzi** [deathlyrage/theisle-bugs#50]
Version:  0.1.15.4141
Tested first by Wuzi on "Primal Core 1 [LowPP/Scent]" (no active mods)

Desc: if you are in a group (herbi group) and one of those herbis got nested as a carni (in our test as giga) then this guy is still in the herbi group therefore it is possible to talk with herbis and carnis

**Comment by Souretsu** [comment]
This happens when changing species as well.  As long as a player is not killed or kicked from the group they will stay in it under any circumstances. Might be intentional?

**Comment by deathlyrage** [comment]
Fixed in 4161
