### ISSUE TITLE
Austro regs stamina while running

### ISSUE THREAD

**Issue by WunderWuzi** [deathlyrage/theisle-bugs#51]
Version:  0.1.15.4141
Tested first by Wuzi on "Primal Core 1 [LowPP/Scent]" (no active mods)
and on some sandbox server
bug confirmed by several different players

Desc: 
Austro has high stamina reg even if he is running means he is able to run for an infinite amount of time

**Comment by WunderWuzi** [comment]
confirmed by several different players

**Comment by MarianaBoni** [comment]
Austro is already fixed http://steamcommunity.com/games/TheIsle/announcements/detail/1449449617889342721
