### ISSUE TITLE
Baby meatballs

### ISSUE THREAD

**Issue by WunderWuzi** [deathlyrage/theisle-bugs#52]
Version: 0.1.15.4141
Tested first by Wuzi on "Primal Core 1 [LowPP/Scent]" (no active mods)

Desc:
it seems like that babys sometimes turn into meatballs if they die.
first i encounterd that bug with a trike baby that died cause of bleed
tried to reproduce it with no special result
also happend to severel other dino babys but its almost impossible to reproduce it

screen for proofment:
https://cdn.discordapp.com/attachments/325277132932644877/343078630588547073/20170804153036_1.jpg

**Comment by AroraTitania** [comment]
Can confirm that. Happened to my Avaceratops juvenile today.
