### ISSUE TITLE
Austroraptor is missing his eyes

### ISSUE THREAD

**Issue by AroraTitania** [deathlyrage/theisle-bugs#53]
Austroraptors eyes are triangles without the new eye sockets in -> holes in model.

![20170806053358_1](https://user-images.githubusercontent.com/26965930/29002202-85a69e20-7a9d-11e7-9ee0-bc9e88cc04e1.jpg)
![20170806053401_1](https://user-images.githubusercontent.com/26965930/29002203-85a6ca4e-7a9d-11e7-8599-3de2a2b123fd.jpg)

**Comment by Souretsu** [comment]
I have actually not experienced this issue.  They show up fine for me at any graphics setting.  Though apparently not for a friend whom I was playing with.

My screenshot:
![20170815012227_1](https://user-images.githubusercontent.com/26914945/29321657-24ac53d6-81a9-11e7-903c-76e665a7527d.jpg)

Friend's screenshot:
https://media.discordapp.net/attachments/238686824254537728/346886522899005440/unknown.png?width=780&height=468

**Comment by deathlyrage** [comment]
Seems to only be a problem for users who don't meet the min spec, also seems to have disappeared recently.
