### ISSUE TITLE
Oro and Taco camera clips through hills/mountains

### ISSUE THREAD

**Issue by AroraTitania** [deathlyrage/theisle-bugs#54]
[Tested on Dev Branch, no mods, region 2]

Orodromeus and Psittacosaurus camera clips throug hills and mountains if you stand too close to them which allows you to see through the map from underneath. 

![20170806045152_1](https://user-images.githubusercontent.com/26965930/29002251-8c16fd08-7a9e-11e7-891c-5840be54c24f.jpg)
![20170806120402_1](https://user-images.githubusercontent.com/26965930/29002309-9f3284ec-7a9f-11e7-9d9b-40533226cae3.jpg)

**Comment by MarianaBoni** [comment]
Not exclusive to these 2 species. Most species do this if not all.

**Comment by AroraTitania** [comment]
Dryo is not having that issue. I will update it should I find more species having that bug.

**Comment by dinosauriac** [comment]
@MarianaBoni @AroraTitania does this happen on every map? It could potentially be an issue with the landscape, not the camera.
