### ISSUE TITLE
Galli's trot sound is out of sync.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#68]
Galli's trot sound is out of sync.
[https://www.youtube.com/watch?v=kqlCgUmNRGE&feature=youtu.be](url)

**Comment by dinosauriac** [comment]
It still kinda needs an actual trot animation, is why.

**Comment by dinosauriac** [comment]
As of SVN version 4379 this should be fine now. There was no animation assigned when trotting, so I subbed in a speed-adjusted walk cycle as a temp trot. Syncs should be working 100%.

Ideally we'd get a custom trot for it, but unless it gets selected for Survival mode I don't think that'll happen, and the current solution works well enough.
