### ISSUE TITLE
(Roar animations) Giga and Spino stretch their body when they get up and roar.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#69]
Patch: 4224
Server: Any.
When you roar while getting up as Spino and Giga, their bodies stretch up.
![376210_screenshots_20170817161511_1](https://user-images.githubusercontent.com/30121219/29432655-5353f42c-8394-11e7-877c-ab737126cba1.jpg)
![_d5145c18f3076d034e3fcc4dd5f0c9d0-jpg](https://user-images.githubusercontent.com/30121219/29432661-58cd8e68-8394-11e7-9708-e2f2bbe9eaf2.jpg)

**Comment by deathlyrage** [comment]
Fixed
