### ISSUE TITLE
New Dedicated Testing Map

### ISSUE THREAD

**Issue by deathlyrage** [deathlyrage/theisle-bugs#7]
Map needs to be made specifically for testing it should include:
- [ ] All Editable Vegetation
- [ ] All Drinkable Water Types
- [ ] All the Dinosaurs in a dedicated section of the map with a AIController set so they can be killed
- [ ] Buttons that you can 'step' on as a dinosaur to reset all the bodies, delete all bodies on the map. Give debug progression points etc
- [ ] Various Test Surfaces such as Staircase, Hills, Forrest, Lake
- [ ] Use the same terrain shader that we are planning on using on V4.
- [ ] Debug Kill Areas such as Lava

**Comment by Hypno123** [comment]
DV_TestLevel meets the criteria.
