### ISSUE TITLE
Oro's camera isn't centered when zoomed in.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#75]
Patch: 4260
Oro's camera is positioned to it's left when zoomed in.
![20170825001740_1](https://user-images.githubusercontent.com/30121219/29692736-871eb55e-8929-11e7-88e0-4523e4f3e7d9.jpg)

**Comment by Paleocolour** [comment]
I cannot reproduce this bug. Patch 4392.

**Comment by Paleocolour** [comment]
Closed as per Deathly's instructions.
