### ISSUE TITLE
Cerato's Camera glitches through the ground

### ISSUE THREAD

**Issue by WunderWuzi** [deathlyrage/theisle-bugs#81]
Game Version: 0.1.16.4262
Tested by Wuzi on "Primal Core[LowPP]" (no Mods)
Date: 25.08.2017, 08:00 PM CET

ceratos camera can glitch through the ground

**Comment by MarianaBoni** [comment]
Already reported here https://github.com/deathlyrage/theisle-bugs/issues/46
Make sure to read all the reports.
