### ISSUE TITLE
Adult Rex appears twice on the sandbox character selection.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#87]
Patch: 4290
Server: Any with sandbox.
Adult Rex appears twice on the sandbox character selection but with different names.
![20170901005614_1](https://user-images.githubusercontent.com/30121219/29950005-d66cb08e-8eb0-11e7-84c4-b394a819af56.jpg)

**Comment by Paleocolour** [comment]
This has to do with how the CharacterSelectList has every dinosaur thrown into it at the moment, including the Survival Mode T. rexes. The two lists should either be seperated or a flag should be created in the list to indicate survival/sandbox dinosaurs.
