### ISSUE TITLE
Nesting issues.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#93]
Patch:
Server: NY8 
- If a nest gets destroyed and you relog, it shows 4 eggs. **(Fixed)**
- There is a time delay of around 5 seconds from adding food to nest and it appearing in the nest UI.

- When you relog and are far away from the nest, the icon doesn't show up. It only starts showing up when you're close to it again. **(Fixed)**
- When you die, your previous nest doesn't reset and you can still see the icon for it. You can also set up a new nest and both icons appear. **(Fixed)**
![screenshot_3](https://user-images.githubusercontent.com/30121219/30117901-8425668c-9319-11e7-9755-0ef8e47a4d0a.png)

- Some animals are unable to destroy their nests. (Camara, puerta)
- Players are able to nest while swimming. **(Fixed)**
![20170906234512_1](https://user-images.githubusercontent.com/30121219/30137922-8f59df9e-935d-11e7-9814-6245f6f88aa1.jpg)

**Comment by Hypno123** [comment]
To add to this, nests sometimes delay when destroyed, ranging between instantly changing to taking up to 20 seconds for appearance change.

**Comment by Tootsiepooh** [comment]
Just tested this: Theri can destroy its nest. It requires the nest to be directly in front of your feet, look directly downwards and use the M1 or M2 attack.

**Comment by AroraTitania** [comment]
Theris nest symbol disappears after relogging.
